import { readFile, readdir, unlink, writeFile } from "node:fs/promises";
import { mkdir } from "node:fs/promises";
import { join } from "node:path";

const fullManifestChunkPattern = /^responsive-images-full-(\d+)\.js$/u;
const fullManifestChunkSize = 100;

export function renderManifest(entries, exportName = "responsiveImages") {
  return `// Generated by scripts/generate-responsive-images.mjs. Do not edit by hand.\n`
    + `const ${exportName} = Object.freeze(${JSON.stringify(entries, null, 2)});\n\n`
    + `export { ${exportName} };\n`;
}

export function chunkResponsiveEntries(entries, chunkSize = fullManifestChunkSize) {
  if (!Number.isInteger(chunkSize) || chunkSize < 1) throw new Error("响应式图片清单分块大小必须是正整数。");
  const pairs = Array.isArray(entries) ? entries : Object.entries(entries || {});
  return Array.from({ length: Math.ceil(pairs.length / chunkSize) }, (_, index) => (
    Object.fromEntries(pairs.slice(index * chunkSize, (index + 1) * chunkSize))
  ));
}

export function responsiveImageChunkMap(chunks) {
  return Object.fromEntries(chunks.flatMap((chunk, index) => Object.keys(chunk).map((source) => [source, index])));
}

async function existingFullManifestChunks(manifestDirectory) {
  const names = await readdir(manifestDirectory).catch((error) => {
    if (error.code === "ENOENT") return [];
    throw error;
  });
  return names.filter((name) => name === "responsive-images-full.js" || fullManifestChunkPattern.test(name)).sort((left, right) => left.localeCompare(right));
}

export async function writeBuildManifest(entries, { check = false, manifestDirectory }) {
  const outputPath = join(manifestDirectory, "responsive-images-build.json");
  const renderedIndex = `${JSON.stringify(entries, null, 2)}\n`;
  const currentNames = await existingFullManifestChunks(manifestDirectory);
  if (check) {
    const currentIndex = await readFile(outputPath, "utf8").catch(() => "");
    return currentIndex === renderedIndex && currentNames.length === 0;
  }
  await mkdir(manifestDirectory, { recursive: true });
  await Promise.all([
    writeFile(outputPath, renderedIndex),
    ...currentNames.map((name) => unlink(join(manifestDirectory, name))),
  ]);
  return true;
}
