// Generated by scripts/generate-content-targets.mjs. Do not edit by hand.
const targets = {
  "post": [
    "site-about",
    "site-friends"
  ],
  "poem": [],
  "music": []
};

const targetSets = Object.fromEntries(
  Object.entries(targets).map(([type, slugs]) => [type, new Set(slugs)]),
);

export function isStaticContentTarget(type, slug) {
  return targetSets[type]?.has(slug) || false;
}

export { targets as staticContentTargets };
