import { useEffect, useMemo, useState } from "react";
import { Check } from "@phosphor-icons/react/Check";
import { CopySimple } from "@phosphor-icons/react/CopySimple";
import { Highlight, themes } from "prism-react-renderer";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { ArticleBlockquote, MermaidDiagram } from "./components/ArticleBodyFeatures.jsx";
import "./components/ArticleBodyFeatures.css";
import { hasMathSyntax, isMermaidLanguage, protectCurrencySyntax } from "./content/richFeatures.js";
import { detailImageSizes } from "./responsiveImages.ts";
import { getPostMarkdown, getPostOutline } from "./richContent.js";
import { isApplicationRoute, legacyHashRoute, routeHref } from "./routes.js";
import { ZoomableImage } from "./ZoomableImage.jsx";

const languageNames = {
  bash: "Terminal — bash",
  shell: "Terminal — shell",
  sh: "Terminal — sh",
  zsh: "Terminal — zsh",
  console: "Terminal",
  js: "JavaScript",
  javascript: "JavaScript",
  jsx: "React JSX",
  ts: "TypeScript",
  typescript: "TypeScript",
  tsx: "React TSX",
  css: "CSS",
  html: "HTML",
  json: "JSON",
  python: "Python",
  py: "Python",
  markdown: "Markdown",
  md: "Markdown",
};

function CodeWindow({ children }) {
  const codeElement = Array.isArray(children) ? children[0] : children;
  const className = codeElement?.props?.className || "";
  const language = className.match(/language-([\w-]+)/)?.[1] || "text";
  const code = String(codeElement?.props?.children ?? "").replace(/\n$/, "");
  const [copied, setCopied] = useState(false);
  const terminal = ["bash", "shell", "sh", "zsh", "console"].includes(language);

  const copyCode = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1600);
    } catch {
      setCopied(false);
    }
  };

  return <section className={terminal ? "code-window code-window--terminal" : "code-window"} aria-label={`${languageNames[language] || language} 代码块`}>
    <header className="code-window-bar">
      <span className="code-window-lights" aria-hidden="true"><i /><i /><i /></span>
      <span className="code-window-title">{languageNames[language] || language.toUpperCase()}</span>
      <button type="button" onClick={copyCode} aria-label="复制代码">{copied ? <Check size={15} weight="bold" /> : <CopySimple size={15} />}<span>{copied ? "已复制" : "复制"}</span></button>
    </header>
    <div className="code-window-body">
      <Highlight theme={themes.vsDark} code={code} language={language === "text" ? "markup" : language}>
        {({ className: highlightClass, style, tokens, getLineProps, getTokenProps }) => <code className={highlightClass} style={style}>
          {tokens.map((line, lineIndex) => {
            const lineProps = getLineProps({ line });
            return <span {...lineProps} className={`code-line ${lineProps.className || ""}`} key={lineIndex}>
              {tokens.length > 1 && <span className="code-line-number" aria-hidden="true">{lineIndex + 1}</span>}
              <span className="code-line-copy">{line.map((token, tokenIndex) => <span {...getTokenProps({ token })} key={tokenIndex} />)}</span>
            </span>;
          })}
        </code>}
      </Highlight>
    </div>
  </section>;
}

function RichImage({ src, alt = "", title }) {
  return <ZoomableImage src={src} alt={alt} caption={title} sizes={detailImageSizes} triggerClassName="article-inline-image" />;
}

function MarkdownPre({ children }) {
  const codeElement = Array.isArray(children) ? children[0] : children;
  const className = codeElement?.props?.className || "";
  const language = className.match(/language-([\w-]+)/)?.[1] || "text";
  if (isMermaidLanguage(language)) {
    return <MermaidDiagram source={String(codeElement?.props?.children ?? "").replace(/\n$/u, "")} />;
  }
  return <CodeWindow>{children}</CodeWindow>;
}

/**
 * Keep authored links to application pages on the same canonical pathname
 * format as links generated by the theme. Ordinary fragments, assets and
 * external URLs retain their browser-native behavior.
 * @param {unknown} href
 * @returns {string|undefined}
 */
function markdownHref(href) {
  if (href == null) return undefined;
  const value = String(href);
  const legacy = legacyHashRoute(value);
  if (legacy) return legacy;
  if (!value.startsWith("/") || value.startsWith("//")) return value;
  try {
    const url = new URL(value, typeof window === "undefined" ? "https://fonscape.invalid" : window.location.origin);
    if (!isApplicationRoute(url.pathname)) return value;
    return routeHref(url.pathname, url.search);
  } catch {
    return value;
  }
}

const components = {
  pre: MarkdownPre,
  code: ({ className, children }) => <code className={className}>{children}</code>,
  img: RichImage,
  table: ({ children }) => <div className="article-table-wrap" tabIndex="0"><table>{children}</table></div>,
  blockquote: ArticleBlockquote,
  a: ({ href, children }) => {
    const normalizedHref = markdownHref(href);
    const external = normalizedHref?.startsWith("http");
    return <a href={normalizedHref} target={external ? "_blank" : undefined} rel={external ? "noreferrer" : undefined}>{children}</a>;
  },
};

let mathPluginsPromise;

function loadMathPlugins() {
  if (!mathPluginsPromise) {
    mathPluginsPromise = Promise.all([
      import("remark-math").then((module) => module.default || module),
      import("rehype-katex").then((module) => module.default || module),
      import("katex/dist/katex.min.css"),
    ]).then(([remarkMath, rehypeKatex]) => ({ remarkMath, rehypeKatex }));
    mathPluginsPromise = mathPluginsPromise.catch((error) => {
      mathPluginsPromise = undefined;
      throw error;
    });
  }
  return mathPluginsPromise;
}

export function RichArticleContent({ post, inlineMusicPlayer = null, inlineMusicPlayers = {} }) {
  const markdown = getPostMarkdown(post);
  const outline = useMemo(() => getPostOutline(post), [post]);
  const headings = useMemo(() => outline.filter((item) => !item.prologue), [outline]);
  const mathInMarkdown = useMemo(() => hasMathSyntax(markdown), [markdown]);
  const [mathPlugins, setMathPlugins] = useState(null);
  useEffect(() => {
    if (!mathInMarkdown) return undefined;
    let active = true;
    loadMathPlugins().then((plugins) => {
      if (active) setMathPlugins(plugins);
    }).catch(() => {
      if (active) setMathPlugins(null);
    });
    return () => { active = false; };
  }, [mathInMarkdown]);
  const articleComponents = useMemo(() => ({
    ...components,
    h2: ({ children, node }) => {
      const heading = headings.find((item) => item.line === node?.position?.start?.line) || headings[0] || { id: "article-section-1", number: "01" };
      return <h2 id={heading.id}><span className="article-section-number">{heading.number}</span><span>{children}</span></h2>;
    },
    p: ({ children }) => {
      const marker = Array.isArray(children) ? children.join("") : children;
      if (typeof marker === "string" && marker.trim() === "[[article-music]]") return inlineMusicPlayer;
      const musicMarker = typeof marker === "string" ? /^\[\[article-music:([a-zA-Z0-9-]+)\]\]$/u.exec(marker.trim()) : null;
      if (musicMarker) return inlineMusicPlayers[musicMarker[1]] || null;
      return <p>{children}</p>;
    },
  }), [headings, inlineMusicPlayer, inlineMusicPlayers]);
  const remarkPlugins = useMemo(() => mathInMarkdown && mathPlugins ? [remarkGfm, mathPlugins.remarkMath] : [remarkGfm], [mathInMarkdown, mathPlugins]);
  const rehypePlugins = useMemo(() => mathInMarkdown && mathPlugins ? [mathPlugins.rehypeKatex] : undefined, [mathInMarkdown, mathPlugins]);
  const renderedMarkdown = mathInMarkdown && mathPlugins ? protectCurrencySyntax(markdown) : markdown;
  return <div className={`article-body rich-article${headings.length > 1 ? " has-outline" : ""}`}>
    <div className="article-prose">{outline[0]?.prologue && <span id="article-prologue" className="article-prologue-anchor" aria-hidden="true" />}<ReactMarkdown remarkPlugins={remarkPlugins} rehypePlugins={rehypePlugins} components={articleComponents}>{renderedMarkdown}</ReactMarkdown></div>
  </div>;
}
